// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRaSIK52Fi9p__pV1QkXhzQdfiqrdXdjs',
    appId: '1:107181361080:web:eda9a48edbf1e5813c714d',
    messagingSenderId: '107181361080',
    projectId: 'bookstore-8c76b',
    authDomain: 'bookstore-8c76b.firebaseapp.com',
    storageBucket: 'bookstore-8c76b.firebasestorage.app',
    measurementId: 'G-QNX497E2NG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjLL8RZ7YJ0SCDcaYXmVBTLwn5OOX1Ldg',
    appId: '1:107181361080:android:16323498d4de2bd73c714d',
    messagingSenderId: '107181361080',
    projectId: 'bookstore-8c76b',
    storageBucket: 'bookstore-8c76b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMF5uozQr65XTiNdGsf3NYIpXhAwkiF8A',
    appId: '1:107181361080:ios:c773158e4bc72e113c714d',
    messagingSenderId: '107181361080',
    projectId: 'bookstore-8c76b',
    storageBucket: 'bookstore-8c76b.firebasestorage.app',
    iosClientId: '107181361080-1h3459dmrtf757ea6m5hlvbv1n2tovmm.apps.googleusercontent.com',
    iosBundleId: 'com.example.book',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMF5uozQr65XTiNdGsf3NYIpXhAwkiF8A',
    appId: '1:107181361080:ios:c773158e4bc72e113c714d',
    messagingSenderId: '107181361080',
    projectId: 'bookstore-8c76b',
    storageBucket: 'bookstore-8c76b.firebasestorage.app',
    iosClientId: '107181361080-1h3459dmrtf757ea6m5hlvbv1n2tovmm.apps.googleusercontent.com',
    iosBundleId: 'com.example.book',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRaSIK52Fi9p__pV1QkXhzQdfiqrdXdjs',
    appId: '1:107181361080:web:26a3c4802031813a3c714d',
    messagingSenderId: '107181361080',
    projectId: 'bookstore-8c76b',
    authDomain: 'bookstore-8c76b.firebaseapp.com',
    storageBucket: 'bookstore-8c76b.firebasestorage.app',
    measurementId: 'G-T3L84407CJ',
  );

}